### ISSUE TITLE
Differing results between lineages.csv and output lineage

### ISSUE THREAD

**Issue by Richardharrigan** [hCoV-2019/pangolin#11]
Hi
Excellent work - thank you!  
I downloaded lineages.csv and selected the ~147 ones with "Representative = 1".  When I processed these, there were twelve (see attached
[discordant.txt](https://github.com/hCoV-2019/pangolin/files/4472176/discordant.txt)
) which changed lineage between the input lineage.csv and the output lineage_report.csv.    (This may have something to do with an alignment step I did). 

The median bootstrap values were lower in those with different reported lineages vs those that agreed (89.5 vs 94), but I was struck by the fact that all the discordant ones were either originally B10 (N=5), B1.10 (N=4) or B3.1 (N=3), and there did not appear to be any from those three lineages which DID agree. 

Cheers

**Comment by aineniamh** [comment]
Thanks for that. With new data it seemed that some of the lineages weren't as well resolved as they appeared with more data. We're now running `-au` flags as well as `-alrt 1000` in addition to the ultrafast bootstrap we'd previously been running.  The `-au` flag should throw away any particularly bad trees. Currently testing the full set of lastest data from gisaid against the new guide tree and anything discordant I'll re-evaluate. 
I do think that the UFbootstrap values need to be interpreted with caution though, so we're now reporting the SH-alrt value as well as the UFbootstrap value.
