### ISSUE TITLE
B.4 cannot be parented by both B and B.4.1!

### ISSUE THREAD

**Issue by joshsinger** [hCoV-2019/pangolin#14]
This is a snippet from anonymised.aln.fasta.treefile:

![treefile_snippet](https://user-images.githubusercontent.com/12393081/79217088-2615e100-7e46-11ea-87b7-afbe21894156.png)

The location of 175_B.4 implies (as we would expect) that lineage B.4 is parented by B. 
But the location of 72_B.4 implies that B.4 is parented by B.4.1. 

Something is wrong, I think.

I wonder if the assignment of 72_B.4 might be a mistake here. The bootstraps indicate it could be a member of B.4.2.

**Comment by rambaut** [comment]
B.4.1 and B.4.2 have been removed in the latest version. All these should be B.4 (the labelling was not updated correctly).

**Comment by joshsinger** [comment]
OK, I thought it might be my mistake / misunderstanding.
