### ISSUE TITLE
Should B.10 be renamed B.7.1?

### ISSUE THREAD

**Issue by joshsinger** [hCoV-2019/pangolin#15]
B.10 is wholly contained within B.7 in the tree. I would've thought, following the naming convention, it would be named B.7.1. It's the only case of this in the whole tree.  What's the justification? Is this likely to happen much in the future?

**Comment by rambaut** [comment]
It is not wholly contained in B.7 in my tree.

**Comment by rambaut** [comment]
Yes. It looks like this is two Hong Kong clades that split apart in the tree (with low bootstrap). Will look into this.

**Comment by aineniamh** [comment]
To follow up on this, we have removed B.10 as a lineage for the moment. Those sequences are now just considered B.7. We will revisit this as new data comes in again.

**Comment by joshsinger** [comment]
Thanks
