### ISSUE TITLE
questions about how to interpret the bootstrap column

### ISSUE THREAD

**Issue by rainwala** [hCoV-2019/pangolin#18]
Hi, 

I think that a boostrap of 95.0 means that 95% of the bootstrapped trees support the assignment -- is that correct? If so,  what does 100/92 and 22/88 mean?

Thanks.

**Comment by aineniamh** [comment]
Hi, if you `git pull` and re-install, this has been fixed as of a few minutes ago! The first value was inherited from the guide tree, but they're now removed from the final report. Should be straightforward bootstraps now!

**Comment by rainwala** [comment]
great, thanks!!

**Comment by rainwala** [comment]
So now, does th number in the bootstrap column mean "the number of boostrap trees, out of 100 tested, that support this lineage assignement"?
