### ISSUE TITLE
So now, does the number in the bootstrap column mean "the number of boostrap trees, out of 100 tested, that support this lineage assignement"?

### ISSUE THREAD

**Issue by rainwala** [hCoV-2019/pangolin#19]
So now, does the number in the bootstrap column mean "the number of boostrap trees, out of 100 tested, that support this lineage assignement"?

_Originally posted by @rainwala in https://github.com/hCoV-2019/pangolin/issues/18#issuecomment-614615113_

**Comment by aineniamh** [comment]
In terms of your question "the number of boostrap trees, out of 100 tested, that support this lineage assignement", we are running 1000 bootstraps but it doesn't doesn't quite correspond to that.  We're running iqtree ultra-fast bootstrapping from [Minh et al., 2013](https://academic.oup.com/mbe/article/30/5/1188/997508) and the iqtree manual describes the bootstrap output as "95% support correspond roughly to a probability of 95% that a clade is true." Its very fast, which is a real benefit, but you may want to only put weight behind UFbootstraps that are quite high.
