### ISSUE TITLE
Will the nomenclature be updated periodically?

### ISSUE THREAD

**Issue by ShaokangZhang** [hCoV-2019/pangolin#2]
Great work! Thanks for providing this.
Will the nomenclature be updated periodically? Like every week?
Regards,
Shaokang

**Comment by aineniamh** [comment]
Hi Shaokang, 
We will be updating regularly and making revisions as we see novel lineages appear. We have been manually curating these lineages ~ weekly up til now and I've updated the guide tree and representative sequence alignment as appropriate. 
Thanks! 
Áine
