### ISSUE TITLE
following on from issue #19

### ISSUE THREAD

**Issue by rainwala** [hCoV-2019/pangolin#20]
continuing the discussion from #19 
OK, thanks, I'm also asking about the way your output is presented. 95 in the last column corresponds to 95% support from what I interpret in your answer -- is that correct?

When you say "quite high", what kind of cutoff would you suggest?

Thank you.

**Comment by aineniamh** [comment]
95 in the last column corresponds to 95 as a UFbootstrap support value taken from the node placement in the tree. The Minh et al 2013 paper I linked you to earlier goes into exactly what that value means and their recommendation for interpretation. 

Bootstraps are resistant to exact cutoffs generally. We're just reporting this value to indiate the level of support for that branch's position in the guide tree and ask that you interpret the result with appropriate caution.

**Comment by rainwala** [comment]
Thank you very much for this answer.
