### ISSUE TITLE
rule pass_query_hash

### ISSUE THREAD

**Issue by andersonbrito** [hCoV-2019/pangolin#21]
Hi,

Thank you for developing this tool. It'll be really helpful, especially when new lineage names are proposed, as more genomes are released.

Just to let you know: the command below crashes the pipeline when a space is found in the path.

```
touch /Users/username/Team Dropbox/User name/working/directory/temp/temp.txt
touch: Dropbox/User: No such file or directory
touch: name/working/directory/temp/temp.txt: No such file or directory
```

Cheers,
Anderson

**Comment by rambaut** [comment]
Fix?: snakemake to use quoting for path names.

**Comment by aineniamh** [comment]
This should be fixed now.

**Comment by aineniamh** [comment]
I've tested it in my own dropbox account so hopefully that'll sort it for you too!
