### ISSUE TITLE
Could you make a documentation of how to use the program? 

### ISSUE THREAD

**Issue by guanq819** [hCoV-2019/pangolin#29]
Hi, 
Thank you for making this program. It is helpful in this global epidemic situation. I was trying to assign some of the genomes to a clade and got this error: 

pangolin query.fasta
Found the snakefile
The query file is /labs/pathogen/data/software/pangolin/EPI_ISL_417156.fasta
Number of threads is 1
MissingInputException in line 3 of /python3.7/site-packages/pangolin/scripts/assign_query_file.smk:
Missing input files for rule decrypt_aln:
/python3.7/site-packages/pangolin/scripts/../data/anonymised.encrypted.aln.fasta

Is the query a fasta file? I have checked the folder but no anonymised.encrypted.aln.fasta file in the folder? 

Thank you.

**Comment by wadhamite** [comment]
I am also getting this error on Ubuntu/MRC Climb

**Comment by aineniamh** [comment]
Hi, pangolin is being updated over this weekend. You're right the file has been removed while we're updating. Early next week if you git pull the latest udpates, pangolin will be back up and running! Sorry for the confusion, I've added a note to the readme.

**Comment by aineniamh** [comment]
The file has been restored now, if you re-install it should work fine now!
