### ISSUE TITLE
Could you share the code?

### ISSUE THREAD

**Issue by andersgs** [hCoV-2019/pangolin#3]
This is related to issue #2. 

It would be useful if there was a tool that would automatically place new sequences in their lineages, or name a new lineage.

Thank you.

**Comment by aineniamh** [comment]
"automatically place new sequences in their lineages"
So this is what pangolin does! 
Currently we haven't automated naming new lineages as to do it well requires knowledge of metadata, including epidemiological information and country links, as well as the genetic data. In the future we may implement a system that flags up certain parts of the phylogeny as 'putative lineages', but we think there'll always need to be some level of manual curation.
