### ISSUE TITLE
Honour $TMPDIR or allow user to choose it?

### ISSUE THREAD

**Issue by tseemann** [hCoV-2019/pangolin#30]
As i understand it, you are using `temp` in `-o` (outdir) for all the temp files.

Ideally `os.tmpdir()` would be used so that it would honour `$TMPDIR` which is usually super fast storage.

Would this be possible?

**Comment by aineniamh** [comment]
Temp directory is now`tempfile.gettempdir()`, which defaults to $TMPDIR. Can be overwritten by optional`--tempdir` parameter.
