### ISSUE TITLE
Alternative handling of 'bad' sequences

### ISSUE THREAD

**Issue by tseemann** [hCoV-2019/pangolin#34]
When i run on a sequence with >50% `N` pangolin exits with errcode 1 and outputs nothing.

Would it be possible to add an option to put this in the report instead?

```
% cat lineage_report.csv

ID,lineage,BS,ALRT
good,A.1,84,98
bad,-,0,0
```
maybe even add a `Note` column saying why it failed?

**Comment by tseemann** [comment]
Maybe a column of `Percent_N`  for each isolate too?
As you calculate it anyway for the 50% cutoff.

**Comment by aineniamh** [comment]
It'll now output bad sequences and not break. 
Checks for N content and minimum sequence length. 
`--max-ambig `, `--min-length` now optional parameters with defaults 0.5 and 10000. 
Output csv file now looks like:
```
taxon,lineage,SH-alrt,UFbootstrap,status,note
good_seq_1,B,100,96,success,
good_seq_2,B.1,0,0,success,
this_seq_has_no_seq,None,0,0,fail,seq_len:0
this_seq_is_too_short,None,0,0,fail,seq_len:2997
this_seq_has_lots_of_Ns,None,0,0,fail,N_content:0.976457211651005
this_seq_is_literally_just_N,None,0,0,fail,N_content:1.0
```
