### ISSUE TITLE
Would you consider adding the version number to the output csv?

### ISSUE THREAD

**Issue by Richardharrigan** [hCoV-2019/pangolin#35]
Thanks!

**Comment by tseemann** [comment]
Yes this is a good idea. The pangolin database should be versioned.

**Comment by aineniamh** [comment]
The plan is to have the database versioned externally (hopefully very soon) and pangolin can have a stable release independent of data versions. Will add the database version (dated) into the csv, good idea.

**Comment by aineniamh** [comment]
This is done now. Pulls data release version from hCov-2019/lineages repo and outputs it in the csv.
