### ISSUE TITLE
attributeError?

### ISSUE THREAD

**Issue by vscooper** [hCoV-2019/pangolin#36]
Hello, would be grateful if you could troubleshoot this error preventing successful analysis. The empty command runs fine in a conda environment.
AttributeError in line 59 of /Users/cooperv/anaconda3/lib/python3.7/site-packages/pangolin/scripts/assign_query_file.smk:
'Workflow' object has no attribute 'cores'
  File "/Users/cooperv/anaconda3/lib/python3.7/site-packages/pangolin/scripts/Snakefile", line 24, in <module>
  File "/Users/cooperv/anaconda3/lib/python3.7/site-packages/pangolin/scripts/assign_query_file.smk", line 59, in <module>

**Comment by tseemann** [comment]
The code was updated 2 hours before this message so I wonder if it's currently in a broken state?

Try `pip3 install --upgrade git+https://github.com/hCoV-2019/pangolin.git`

**Comment by aineniamh** [comment]
I don't think it's related, I just updated the guide tree and alignment. 
It seems like a snakemake version issue perhaps? The pangolin environment should have python 3.6 and snakemake 5.13, but your error is saying python 3.7. 
Shouldn't matter but maybe just double check the versions you're running?

**Comment by vscooper** [comment]
Thanks folks, still no luck after checking versions. However snakemake version 3.13.3 is specified in this environment, not 5.13? Any other ideas? `AttributeError in line 59 of /Users/cooperv/anaconda3/envs/pangolin/lib/python3.6/site-packages/pangolin/scripts/assign_query_file.smk:
'Workflow' object has no attribute 'cores'
  File "/Users/cooperv/anaconda3/envs/pangolin/lib/python3.6/site-packages/pangolin/scripts/Snakefile", line 24, in <module>
  File "/Users/cooperv/anaconda3/envs/pangolin/lib/python3.6/site-packages/pangolin/scripts/assign_query_file.smk", line 59, in <module>
(pangolin) mmg-cooper-2:10707 cooperv$ snakemake --version
3.13.3
`

**Comment by jameshadfield** [comment]
I believe this is due to an outdated Snakemake -- pangolin's conda env [specifies 5.13](https://github.com/hCoV-2019/pangolin/blob/master/environment.yml#L13) and I'm guessing that snakemake 3.x doesn't understand the `--cores` argument

**Comment by aineniamh** [comment]
To solve, you might want to just make the environment again from scratch, something seems to have gone wrong there! `'Workflow' object has no attribute 'cores'` shouldn't be an issue in 5.13. I've just tested the master on macosx and linux and it seems to be running fine in both.
