### ISSUE TITLE
Compare to a solution provided by "curated clades.tsv + nextstrain/augur clade" ?

### ISSUE THREAD

**Issue by biocyberman** [hCoV-2019/pangolin#40]
Hi
I am trying to understand use case of this package. From what I can see `ncov` build of `nextstrain/augur` can use a ["clades.tsv"](https://github.com/nextstrain/ncov/blob/master/config/clades.tsv) file to annotate the whole tree. 

_Pros_: annotate whole tree, `auspice` ready. 

_Cons_: One must have a curated `clades.tsv`. However having a well synced curated clade.tsv file is also very readable, and maintainable (except that there should be a discussion on what to put there). 

From what I can see with `pangolin` so far: It annotate the query sequences, but doesn't annotate internal nodes of my own tree (not the guide tree provided by `pangolin`). This annotation is useful indeed. However, what should I do if I want to annotate the internal nodes (the whole tree) as well? 

Or can I generate `clades.tsv` from another guide tree, alignment and use that for my tree and genomes?

**Comment by aineniamh** [comment]
I don't think what you're trying to do is related to pangolin, we're just assigning lineages to a query sequence based on position in a guide tree. The output is a csv report.

However, annotating nodes in a tree is possible and depending on what information you already have you can do it manually with [FigTree](http://tree.bio.ed.ac.uk/software/figtree/) or  [Dendropy](https://dendropy.org/). Or do trait reconstruction with [RaxML](https://cme.h-its.org/exelixis/web/software/raxml/) or [BEAST](https://beast.community/). You could check those out.

**Comment by biocyberman** [comment]
Thanks for the hints

Actually it is almost perfect for me to run `scripts/defining_snps.py` and get the output. However, the published alignment file `anonymised.encrypted.aln.fasta` is encrypted. So the output is not usable. Or is it? I am not familiar with how the sequence is encrypted, probably only the areas without SNPs.

**Comment by biocyberman** [comment]
@aineniamh Would you please comment on whether `defining_snps.py` expect encrypted alignment file or unencrypted one?

**Comment by aineniamh** [comment]
I'm not supporting running defining_snps.py independently of pangolin. It's a script still in development and there's a reason why its output is not integrated. 

I am working on integrating it into the data prep pipeline and it snps will be an output in the future (will exist in the hCoV-2019/lineages repository, not here). However, this will remain independent of the routine running of pangolin.

**Comment by biocyberman** [comment]
Will check it out further myself. Thanks for the info and the work.
