### ISSUE TITLE
ModuleNotFoundError: No module named 'lineages'

### ISSUE THREAD

**Issue by tseemann** [hCoV-2019/pangolin#49]
pangolin-1.1 master HEAD

```
  File "/opt/bin/pangolin", line 5, in <module>
    from pangolin.command import main
  File "//opt/python/lib/python3.7/site-packages/pangolin/command.py", line 10, in <module>
    import lineages
ModuleNotFoundError: No module named 'lineages'
```

**Comment by tseemann** [comment]
Documentation forgot to mention i need to install a separate package too:
https://github.com/hCoV-2019/lineages.git

Not everyone can use conda.

```
pip3 install --upgrade git+https://github.com/hCoV-2019/pangolin.git git+https://github.com/hCoV-2019/lineages.git
```
this works for bleeding edgers :)

**Comment by aineniamh** [comment]
I had mentioned it in the README under 'updating pangolin', but I've added in some clarification in the installation section for those who can't use conda.

**Comment by tseemann** [comment]
Thank you.
