### ISSUE TITLE
ISO ID Country, Province, city, lat, long missing.

### ISSUE THREAD

**Issue by MarcosMaurelli** [hCoV-2019/pangolin#5]
Hi, i made a desktop app that uses Jhon Hopkins dataset and your data.
It imports your data and export to a xlsx file with geoloc info added so your data can be sorted and compared more easily.
![pandemia1 0](https://user-images.githubusercontent.com/63467569/79012232-36734680-7b3c-11ea-9bdc-ce32b7def78a.jpg)
[lineages.xlsx](https://github.com/hCoV-2019/lineages/files/4462781/lineages.xlsx)
This way it can be easily imported to qgis arcgis or other plataforms for geographic visualization.
I can send you the app if you want ( i have to translate some words first tho)
(it's a csv xls file, change the extension before opening to csv or xls, i had to put xlsx extension in order to drag the file here)
Im a Licenciado en Bioquimica Clínica working here in Argentina.
Thanks for all your hard work.

**Comment by rainwala** [comment]
Hi Marcos, are you considering perhaps making a web interface for your app?

**Comment by aineniamh** [comment]
Hi Marcos, thanks for messaging. I don't think we need this, but it's great to hear the data is being put to good use. Thanks for the offer though!
