### ISSUE TITLE
'NoneType' object has no attribute 'annotations'

### ISSUE THREAD

**Issue by hrwang** [hCoV-2019/pangolin#52]
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/pangolin/bin/assign_lineage.py", line 86, in <module>
    main()
  File "/home/xxx/miniconda3/envs/pangolin/bin/assign_lineage.py", line 80, in main
    lineage = finder.get_lineage()
  File "/home/xxx/miniconda3/envs/pangolin/bin/lineage_finder.py", line 67, in get_lineage
    grandparent_lineage = self.query_node_parent.parent_node.annotations.get_value("lineage")
AttributeError: 'NoneType' object has no attribute 'annotations'

**Comment by aineniamh** [comment]
Could you provide some more information about how you've run and installed pangolin?

**Comment by HouriiyahT** [comment]
@aineniamh Hi, I am getting the same issue. I installed with conda and using with conda environment. With a really small file (20 sequences) it works but with another file of 125 sequences, getting the same error as above.

**Comment by aineniamh** [comment]
Thanks for clarifying, we're looking into it now!

**Comment by jtmccr1** [comment]
This was likely a bug introduced in a recent commit. It should be fixed now.
