### ISSUE TITLE
mafft-profile will be defunct,use mafft --addprofile

### ISSUE THREAD

**Issue by tseemann** [hCoV-2019/pangolin#56]
See bottom of  https://mafft.cbrc.jp/alignment/software/addsequences.html

Difference from the mafft-profile program

The --addprofile option covers all the situations where the mafft-profile program was used.  Morever, the former is applicable to larger datasets than the latter.  Therefore, the mafft-profile program will be deleted in future releases.

**Comment by aineniamh** [comment]
Thanks for that, I've updated the command now.
