### ISSUE TITLE
pangolin --version should return 0 and go to stdout

### ISSUE THREAD

**Issue by tseemann** [hCoV-2019/pangolin#58]
```
% pangolin -v
pangolin: 1.1.4
%  echo $?
255
```
The GNU standard is:
* --version returns 0 (success)
* prints `pangolin x.y.z`  (without the colon)
* prints to stdout (not stderr)

**Comment by aineniamh** [comment]
I realised I just hadn't removed that block of code from earlier on. `argparse` is just handling it now.
