### ISSUE TITLE
Pangolin assignments are vastly different from the those in Nextstrain

### ISSUE THREAD

**Issue by hrwang** [hCoV-2019/pangolin#63]
I am running assignment using the "2020-04-27" version of the software. I found that the assignment I got is very different from those in Nextstrain website. For example, using pangoin, the sequence "Brazil/SPBR-02/2020, EPI_ISL_413016" is assigned to "B.2" lineage with high confidence (Also B.2 in the 'lineages.2020-04-27.csv' file), but in Nextstrain (https://nextstrain.org/ncov/global?c=clade_membership&s=Brazil/SPBR-02/2020), it is "A1a". This is not isolated case, I have found many more. I am wondering what is causing the difference, just notation?

**Comment by hrwang** [comment]
Just eyeballing, I found that the big pattern is that the "A" and "B" are filpped between pangolin and nextstrain.

**Comment by biocyberman** [comment]
I saw the different too. Nextstrain uses a `clades.tsv` file, and tree as input. I guess the two use two different approaches. `Pangolin` seems to do more rigorous calculation, whereas `nextstrain` seems for focus solely on some `clade defining variants`. The result I got from Nextstrain is more specific. And maybe `pagolin` considers the whole sequence, therefore it is harder to find specific hits.

**Comment by aineniamh** [comment]
We're currently in discussion with the maintainers of nextstrain to consolidate our lineage naming schemes, but I don't think the naming schemes you're linking to are currently compatible. 

It's not that they disagree, they're just different systems, we're using lineage designations as detailed in this preprint: https://www.biorxiv.org/content/10.1101/2020.04.17.046086v1.

**Comment by tseemann** [comment]
Does anyone know how the GISAD "S V G" clades are defined?
