### ISSUE TITLE
Conda recipe needs to say iqtree < 2

### ISSUE THREAD

**Issue by tseemann** [hCoV-2019/pangolin#68]
Conda is currently broken 
iqtree 2.x is not compatible with iqtree 1.x
Need to change constraints in recipe

CC: @jts

**Comment by aineniamh** [comment]
I've made it less than two now, just pushed it. I plan to make it compatible with `iqtree v2` soon, but need to read up about where the incompatibilities are and what it'll mean for the output of pangolin.
