### ISSUE TITLE
Trouble with pangolin env

### ISSUE THREAD

**Issue by wadhamite** [hCoV-2019/pangolin#7]
Very basic problem at my end - following installing and setting up miniconda for windows and cloning the pangolin git repo, I get the following error 

(base) C:\Users\charl\COVID19\pangolin>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - mafft
  - iqtree

Do I need to have mafft and iqtree git repos (from elsewhere) in the same folder as pangolin?

Thanks,
Charlotte

**Comment by aineniamh** [comment]
Hi Charlotte, 
I haven't tested the conda recipe in a window's environment, I've just checked it linux and macosx. If you're comfortable getting the dependencies into your path yourself (found in environment.yml), pangolin should work straight off. Alternatively, if you're running windows 10,  I would recommend getting windows subsystem for linux (wsl) to build the conda environment and run pangolin through that.
Hope that helps, 
Áine
