### ISSUE TITLE
Error while installing in Windows

### ISSUE THREAD

**Issue by atulmw** [hCoV-2019/pangolin#74]
I am working as Statistician in National Institute of Virology, Pune, India.
I used Windows Subsystem for Linux, Windows 10.
Then installed Miniconda.
I kept unzipped pangolin-master folder in D:
As instructed, I ran the command "conda env create -f environment.yml" in this folder from Anaconda powershell prompt. I got following error....
Collecting package metadata (repodata.json): done
Solving environment: failed
ResolvePackageNotFound:
    -iqtree[version= '<2']
    -maftt

**Comment by aineniamh** [comment]
Hi, we can't support windows as we have no means of testing it in our lab. If you need to run on windows, I would suggest either installing those dependencies manually (this is a windows-conda issue that it can't find them) and try again. I'm not entirely sure it'll work (it might!) as we [haven't tested](https://github.com/hCoV-2019/pangolin#requirements) `pangolin` on windows. 

Alternatively, I can recommend  either running on the web application: [pangolin.cog-uk.io](https://pangolin.cog-uk.io/) or trying within a unix-based system.

**Comment by atulmw** [comment]
Hi,

Thanks a lot for the quick response.

I tried the web application, found very useful! Thank you for the same!

I am actually not familiar with conda, python or linux. However I will try
out what you have suggested.

Warm regards,
-Atul Walimbe
