### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by mabouelk** [hCoV-2019/pangolin#78]
I got this error when I tried to update the tool

fatal: not a git repository (or any of the parent directories): .git

**Comment by aineniamh** [comment]
If you `pwd`, are you inside the `.git` directory? 

Try `cd ..` and then `git pull`.

**Comment by aineniamh** [comment]
@mabouelk any update on this issue on your end?

**Comment by mabouelk** [comment]
I cd to pangolin directory but I still getting the same error, so I managed to remove the tool and reinstall it again and it worked.

**Comment by aineniamh** [comment]
Okay, great. Glad you have it working at least! I'll close the issue now. Thanks for following up.
