### ISSUE TITLE
Why don't you describe each lineage by a set of mutations

### ISSUE THREAD

**Issue by acx01b** [hCoV-2019/pangolin#9]
For example the Italian-European lineage is C241T C3037T A23403G C14408T
The French New York lineage is C241T C3037T A23403G C14408T G25563T
Some trees might set G25563T as a subtree of C1059T but that's the game and people reporting why they chose alternative mutations/lineages pairs would be interesting.

**Comment by rambaut** [comment]
That is what the phylogenetic tree is doing.

**Comment by acx01b** [comment]
Myself I'm using those clades

`China []
Italy-Europe (4) ["C241T", "C3037T", "A23403G", "C14408T"]
Netherlands ["T514C"]
France-NewYork (5) ["C241T", "C3037T", "A23403G", "C14408T", "G25563T"]
Mulhouse-Benelux ["C241T", "C3037T", "A23403G", "C14408T", "C15324T"]
ItaUkNeBeDeSwi (7) ["C241T", "C3037T", "A23403G", "C14408T", "G28881A", "G28882A", "G28883C"]
USA WestCoast (4) ["C8782T", "T28144C", "C18060T", "A17858G"]
Iran (4) ["G11083T", "G1397A", "T28688C", "G29742T"]
UK (3) ["G26144T", "G11083T", "C14805T"]
Germany-Wales ["G1440A"]
Spain (5) ["C241T", "C3037T", "A23403G", "C14408T", "A20268G"]`

**Comment by acx01b** [comment]
@rambaut  I added your clades to nextstrain tree there http://www.paris8.free.fr/ncov/arambautNextstrain.html?c=clade_membership

**Comment by rainwala** [comment]
I think pangolin now does output the SNPs.

**Comment by aineniamh** [comment]
So we can find the SNPs in each of the sequences, but aren't assigning based on the lineage specific SNPs. We assign based on placement within a phylogeny of representative sequences and this way we can capture more within-lineage diversity than just using SNPs common to all sequences within a lineage.
